name: flutter_basis
description: Start point package for Flutter applications
version: 1.0.6+12
homepage:

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter:

dependencies:
  flutter:
    sdk: flutter

  equatable:

  http:

  get_it:

  url_launcher:

  shared_preferences:

  path_provider:

  dartz:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  assets:
    - assets/