name: flutter_basis
description: Start point package for Flutter applications
version: 1.0.8+14
homepage:

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter:

dependencies:
  flutter:
    sdk: flutter

  equatable:

  http:

  get_it:

  url_launcher:

  shared_preferences:

  path_provider:

  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  assets:
    - assets/