name: flutter_basis
description: Start point package for Flutter applications
version: 1.0.4+6
homepage:

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter:

dependencies:
  flutter:
    sdk: flutter
  get_it:
  shimmer:
  url_launcher:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  assets:
    - assets/